Module10_Django/m09_10_01/killer_instagram/app_instagram/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "app_instagram"

urlpatterns = [
    path("", views.main, name="root"),
    path("upload/", views.upload, name="upload"),
    path("pictures/", views.pictures, name="pictures"),
]

Module10_Django/m09_10_01/killer_instagram/killer_instagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_instagram.urls")),
]

Module10_Django/m09_10_01/killer_instagram/app_instagram/models.py
from django.db import models

# Create your models here.

Module10_Django/m09_10_01/killer_instagram/app_instagram/views.py
from django.shortcuts import render

# Create your views here.


def main(request):
    cat_desc = "Шелдон, глупый рыжий кошак, который постоянно подводит всех вокруг себя своей удивительной неспособностью думать. Его маленький мозг, как будто сделан из ваты. Тем не менее, вся его глупость и неловкость не могут помешать ему быть милым и обаятельным кошачьим существом. Возможно, именно благодаря своей глупости Шелдон становится источником смеха и радости для всех вокруг него."
    return render(
        request,
        "app_instagram\index.html",
        context={"title": "Sheldon's site", "cat_description": cat_desc},
    )


def upload(request):
    return render(
        request,
        "app_instagram/upload.html",
        context={"title": "Upload picture"}
    )


def pictures(request):
    return render(
        request,
        "app_instagram/pictures.html",
        context={"title": "Pictures"}
    )

Module10_Django/m09_10_01/killer_instagram/app_instagram/templates/app_instagram/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{{title}}</title>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_instagram:pictures' %}">Pictures</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'app_instagram:upload' %}">Upload</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">SignIn</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">SignUp</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          {% block my_content %}
          {% endblock %}
    </div>
</body>
</html>

Module10_Django/m09_10_01/killer_instagram/app_instagram/templates/app_instagram/index.html
{%extends "app_instagram/base.html" %}
{% load static %}
{% block my_content %}


<div class="px-4 pt-5 my-5 text-center border-bottom">
    <h1 class="display-4 fw-bold text-body-emphasis">Шелдон - Тупой пушок</h1>
    <div class="col-lg-6 mx-auto">
      <p class="lead mb-4">{{cat_description}}</p>
      <div class="d-grid gap-2 d-sm-flex justify-content-sm-center mb-5">
        <button type="button" class="btn btn-primary btn-lg px-4 me-sm-3">Погладить пушка</button>
        <button type="button" class="btn btn-outline-secondary btn-lg px-4">Дать пушку по жопке</button>
      </div>
    </div>
    <div class="overflow-hidden" style="max-height: 30vh;">
      <div class="container px-5">
        <img src=" {% static 'app_instagram/sheldon.png' %}" alt="Изображение тупого котяха" style="width: 50%; height: auto;" loading="lazy">
    </div>
  </div>
{% endblock %}

Module10_Django/m09_10_01/killer_instagram/app_instagram/templates/app_instagram/pictures.html
{%extends "app_instagram/base.html" %}
{% load static %}
{% block my_content %}


{% endblock %}

Module10_Django/m09_10_01/killer_instagram/app_instagram/templates/app_instagram/upload.html
{%extends "app_instagram/base.html" %}

{% block my_content %}
<h1>Upload file</h1>
<form action=", method='post" enctype="multipart/form-data">
    { % csrf_token % }
    <div class="mb-3">
      <label class="form-label">Description</label>
    </div>
    <div class="mb-3">
      <label class="form-label">Picture</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}